// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11-devel
// 	protoc        v7.34.0
// source: api/orchestrate/v1/orchestrate.proto

package orchestratev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PlanRequest asks the server to compute a plan from the given composition.
type PlanRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	CompositionJson []byte                 `protobuf:"bytes,1,opt,name=composition_json,json=compositionJson,proto3" json:"composition_json,omitempty"`
	Project         string                 `protobuf:"bytes,2,opt,name=project,proto3" json:"project,omitempty"`
	UseCni          bool                   `protobuf:"varint,3,opt,name=use_cni,json=useCni,proto3" json:"use_cni,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PlanRequest) Reset() {
	*x = PlanRequest{}
	mi := &file_api_orchestrate_v1_orchestrate_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlanRequest) ProtoMessage() {}

func (x *PlanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_orchestrate_v1_orchestrate_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlanRequest.ProtoReflect.Descriptor instead.
func (*PlanRequest) Descriptor() ([]byte, []int) {
	return file_api_orchestrate_v1_orchestrate_proto_rawDescGZIP(), []int{0}
}

func (x *PlanRequest) GetCompositionJson() []byte {
	if x != nil {
		return x.CompositionJson
	}
	return nil
}

func (x *PlanRequest) GetProject() string {
	if x != nil {
		return x.Project
	}
	return ""
}

func (x *PlanRequest) GetUseCni() bool {
	if x != nil {
		return x.UseCni
	}
	return false
}

// Action describes a single planned change.
type Action struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"` // "create", "update", "destroy", "noop"
	ResourceId    string                 `protobuf:"bytes,2,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	Kind          string                 `protobuf:"bytes,3,opt,name=kind,proto3" json:"kind,omitempty"`
	Reason        string                 `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Action) Reset() {
	*x = Action{}
	mi := &file_api_orchestrate_v1_orchestrate_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Action) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Action) ProtoMessage() {}

func (x *Action) ProtoReflect() protoreflect.Message {
	mi := &file_api_orchestrate_v1_orchestrate_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Action.ProtoReflect.Descriptor instead.
func (*Action) Descriptor() ([]byte, []int) {
	return file_api_orchestrate_v1_orchestrate_proto_rawDescGZIP(), []int{1}
}

func (x *Action) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Action) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

func (x *Action) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *Action) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// PlanResponse returns the computed plan.
type PlanResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Actions       []*Action              `protobuf:"bytes,1,rep,name=actions,proto3" json:"actions,omitempty"`
	Creates       int32                  `protobuf:"varint,2,opt,name=creates,proto3" json:"creates,omitempty"`
	Updates       int32                  `protobuf:"varint,3,opt,name=updates,proto3" json:"updates,omitempty"`
	Destroys      int32                  `protobuf:"varint,4,opt,name=destroys,proto3" json:"destroys,omitempty"`
	Noops         int32                  `protobuf:"varint,5,opt,name=noops,proto3" json:"noops,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlanResponse) Reset() {
	*x = PlanResponse{}
	mi := &file_api_orchestrate_v1_orchestrate_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlanResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlanResponse) ProtoMessage() {}

func (x *PlanResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_orchestrate_v1_orchestrate_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlanResponse.ProtoReflect.Descriptor instead.
func (*PlanResponse) Descriptor() ([]byte, []int) {
	return file_api_orchestrate_v1_orchestrate_proto_rawDescGZIP(), []int{2}
}

func (x *PlanResponse) GetActions() []*Action {
	if x != nil {
		return x.Actions
	}
	return nil
}

func (x *PlanResponse) GetCreates() int32 {
	if x != nil {
		return x.Creates
	}
	return 0
}

func (x *PlanResponse) GetUpdates() int32 {
	if x != nil {
		return x.Updates
	}
	return 0
}

func (x *PlanResponse) GetDestroys() int32 {
	if x != nil {
		return x.Destroys
	}
	return 0
}

func (x *PlanResponse) GetNoops() int32 {
	if x != nil {
		return x.Noops
	}
	return 0
}

// ApplyRequest asks the server to plan and apply in one shot.
type ApplyRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	CompositionJson []byte                 `protobuf:"bytes,1,opt,name=composition_json,json=compositionJson,proto3" json:"composition_json,omitempty"`
	Project         string                 `protobuf:"bytes,2,opt,name=project,proto3" json:"project,omitempty"`
	UseCni          bool                   `protobuf:"varint,3,opt,name=use_cni,json=useCni,proto3" json:"use_cni,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ApplyRequest) Reset() {
	*x = ApplyRequest{}
	mi := &file_api_orchestrate_v1_orchestrate_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyRequest) ProtoMessage() {}

func (x *ApplyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_orchestrate_v1_orchestrate_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyRequest.ProtoReflect.Descriptor instead.
func (*ApplyRequest) Descriptor() ([]byte, []int) {
	return file_api_orchestrate_v1_orchestrate_proto_rawDescGZIP(), []int{3}
}

func (x *ApplyRequest) GetCompositionJson() []byte {
	if x != nil {
		return x.CompositionJson
	}
	return nil
}

func (x *ApplyRequest) GetProject() string {
	if x != nil {
		return x.Project
	}
	return ""
}

func (x *ApplyRequest) GetUseCni() bool {
	if x != nil {
		return x.UseCni
	}
	return false
}

// ApplyResponse returns the result of the apply.
type ApplyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Actions       []*Action              `protobuf:"bytes,1,rep,name=actions,proto3" json:"actions,omitempty"`
	Creates       int32                  `protobuf:"varint,2,opt,name=creates,proto3" json:"creates,omitempty"`
	Updates       int32                  `protobuf:"varint,3,opt,name=updates,proto3" json:"updates,omitempty"`
	Destroys      int32                  `protobuf:"varint,4,opt,name=destroys,proto3" json:"destroys,omitempty"`
	Noops         int32                  `protobuf:"varint,5,opt,name=noops,proto3" json:"noops,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyResponse) Reset() {
	*x = ApplyResponse{}
	mi := &file_api_orchestrate_v1_orchestrate_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyResponse) ProtoMessage() {}

func (x *ApplyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_orchestrate_v1_orchestrate_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyResponse.ProtoReflect.Descriptor instead.
func (*ApplyResponse) Descriptor() ([]byte, []int) {
	return file_api_orchestrate_v1_orchestrate_proto_rawDescGZIP(), []int{4}
}

func (x *ApplyResponse) GetActions() []*Action {
	if x != nil {
		return x.Actions
	}
	return nil
}

func (x *ApplyResponse) GetCreates() int32 {
	if x != nil {
		return x.Creates
	}
	return 0
}

func (x *ApplyResponse) GetUpdates() int32 {
	if x != nil {
		return x.Updates
	}
	return 0
}

func (x *ApplyResponse) GetDestroys() int32 {
	if x != nil {
		return x.Destroys
	}
	return 0
}

func (x *ApplyResponse) GetNoops() int32 {
	if x != nil {
		return x.Noops
	}
	return 0
}

// TeardownRequest asks the server to tear down services.
type TeardownRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Project         string                 `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	Timeout         int32                  `protobuf:"varint,2,opt,name=timeout,proto3" json:"timeout,omitempty"`
	RemoveVolumes   bool                   `protobuf:"varint,3,opt,name=remove_volumes,json=removeVolumes,proto3" json:"remove_volumes,omitempty"`
	CompositionJson []byte                 `protobuf:"bytes,4,opt,name=composition_json,json=compositionJson,proto3" json:"composition_json,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TeardownRequest) Reset() {
	*x = TeardownRequest{}
	mi := &file_api_orchestrate_v1_orchestrate_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TeardownRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TeardownRequest) ProtoMessage() {}

func (x *TeardownRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_orchestrate_v1_orchestrate_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TeardownRequest.ProtoReflect.Descriptor instead.
func (*TeardownRequest) Descriptor() ([]byte, []int) {
	return file_api_orchestrate_v1_orchestrate_proto_rawDescGZIP(), []int{5}
}

func (x *TeardownRequest) GetProject() string {
	if x != nil {
		return x.Project
	}
	return ""
}

func (x *TeardownRequest) GetTimeout() int32 {
	if x != nil {
		return x.Timeout
	}
	return 0
}

func (x *TeardownRequest) GetRemoveVolumes() bool {
	if x != nil {
		return x.RemoveVolumes
	}
	return false
}

func (x *TeardownRequest) GetCompositionJson() []byte {
	if x != nil {
		return x.CompositionJson
	}
	return nil
}

// TeardownResponse is empty on success.
type TeardownResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TeardownResponse) Reset() {
	*x = TeardownResponse{}
	mi := &file_api_orchestrate_v1_orchestrate_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TeardownResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TeardownResponse) ProtoMessage() {}

func (x *TeardownResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_orchestrate_v1_orchestrate_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TeardownResponse.ProtoReflect.Descriptor instead.
func (*TeardownResponse) Descriptor() ([]byte, []int) {
	return file_api_orchestrate_v1_orchestrate_proto_rawDescGZIP(), []int{6}
}

// StateRequest queries the current rollout state.
type StateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Project       string                 `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StateRequest) Reset() {
	*x = StateRequest{}
	mi := &file_api_orchestrate_v1_orchestrate_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StateRequest) ProtoMessage() {}

func (x *StateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_orchestrate_v1_orchestrate_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StateRequest.ProtoReflect.Descriptor instead.
func (*StateRequest) Descriptor() ([]byte, []int) {
	return file_api_orchestrate_v1_orchestrate_proto_rawDescGZIP(), []int{7}
}

func (x *StateRequest) GetProject() string {
	if x != nil {
		return x.Project
	}
	return ""
}

// RolloutInfo describes a single resource rollout.
type RolloutInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstanceId    string                 `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	InstanceKey   string                 `protobuf:"bytes,2,opt,name=instance_key,json=instanceKey,proto3" json:"instance_key,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Body          []byte                 `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RolloutInfo) Reset() {
	*x = RolloutInfo{}
	mi := &file_api_orchestrate_v1_orchestrate_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RolloutInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RolloutInfo) ProtoMessage() {}

func (x *RolloutInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_orchestrate_v1_orchestrate_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RolloutInfo.ProtoReflect.Descriptor instead.
func (*RolloutInfo) Descriptor() ([]byte, []int) {
	return file_api_orchestrate_v1_orchestrate_proto_rawDescGZIP(), []int{8}
}

func (x *RolloutInfo) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *RolloutInfo) GetInstanceKey() string {
	if x != nil {
		return x.InstanceKey
	}
	return ""
}

func (x *RolloutInfo) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *RolloutInfo) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

// StateResponse returns all current rollouts.
type StateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rollouts      []*RolloutInfo         `protobuf:"bytes,1,rep,name=rollouts,proto3" json:"rollouts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StateResponse) Reset() {
	*x = StateResponse{}
	mi := &file_api_orchestrate_v1_orchestrate_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StateResponse) ProtoMessage() {}

func (x *StateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_orchestrate_v1_orchestrate_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StateResponse.ProtoReflect.Descriptor instead.
func (*StateResponse) Descriptor() ([]byte, []int) {
	return file_api_orchestrate_v1_orchestrate_proto_rawDescGZIP(), []int{9}
}

func (x *StateResponse) GetRollouts() []*RolloutInfo {
	if x != nil {
		return x.Rollouts
	}
	return nil
}

// HealthRequest checks server and runtime health.
type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_api_orchestrate_v1_orchestrate_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_orchestrate_v1_orchestrate_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_api_orchestrate_v1_orchestrate_proto_rawDescGZIP(), []int{10}
}

// HealthResponse returns health status.
type HealthResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Healthy        bool                   `protobuf:"varint,1,opt,name=healthy,proto3" json:"healthy,omitempty"`
	RuntimeName    string                 `protobuf:"bytes,2,opt,name=runtime_name,json=runtimeName,proto3" json:"runtime_name,omitempty"`
	RuntimeVersion string                 `protobuf:"bytes,3,opt,name=runtime_version,json=runtimeVersion,proto3" json:"runtime_version,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_api_orchestrate_v1_orchestrate_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_orchestrate_v1_orchestrate_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_api_orchestrate_v1_orchestrate_proto_rawDescGZIP(), []int{11}
}

func (x *HealthResponse) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *HealthResponse) GetRuntimeName() string {
	if x != nil {
		return x.RuntimeName
	}
	return ""
}

func (x *HealthResponse) GetRuntimeVersion() string {
	if x != nil {
		return x.RuntimeVersion
	}
	return ""
}

// ExecSyncRequest runs a command synchronously in a service container.
type ExecSyncRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Project       string                 `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	Service       string                 `protobuf:"bytes,2,opt,name=service,proto3" json:"service,omitempty"`
	Cmd           []string               `protobuf:"bytes,3,rep,name=cmd,proto3" json:"cmd,omitempty"`
	Timeout       int64                  `protobuf:"varint,4,opt,name=timeout,proto3" json:"timeout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecSyncRequest) Reset() {
	*x = ExecSyncRequest{}
	mi := &file_api_orchestrate_v1_orchestrate_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecSyncRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecSyncRequest) ProtoMessage() {}

func (x *ExecSyncRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_orchestrate_v1_orchestrate_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecSyncRequest.ProtoReflect.Descriptor instead.
func (*ExecSyncRequest) Descriptor() ([]byte, []int) {
	return file_api_orchestrate_v1_orchestrate_proto_rawDescGZIP(), []int{12}
}

func (x *ExecSyncRequest) GetProject() string {
	if x != nil {
		return x.Project
	}
	return ""
}

func (x *ExecSyncRequest) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *ExecSyncRequest) GetCmd() []string {
	if x != nil {
		return x.Cmd
	}
	return nil
}

func (x *ExecSyncRequest) GetTimeout() int64 {
	if x != nil {
		return x.Timeout
	}
	return 0
}

// ExecSyncResponse returns exec output.
type ExecSyncResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stdout        []byte                 `protobuf:"bytes,1,opt,name=stdout,proto3" json:"stdout,omitempty"`
	Stderr        []byte                 `protobuf:"bytes,2,opt,name=stderr,proto3" json:"stderr,omitempty"`
	ExitCode      int32                  `protobuf:"varint,3,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecSyncResponse) Reset() {
	*x = ExecSyncResponse{}
	mi := &file_api_orchestrate_v1_orchestrate_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecSyncResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecSyncResponse) ProtoMessage() {}

func (x *ExecSyncResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_orchestrate_v1_orchestrate_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecSyncResponse.ProtoReflect.Descriptor instead.
func (*ExecSyncResponse) Descriptor() ([]byte, []int) {
	return file_api_orchestrate_v1_orchestrate_proto_rawDescGZIP(), []int{13}
}

func (x *ExecSyncResponse) GetStdout() []byte {
	if x != nil {
		return x.Stdout
	}
	return nil
}

func (x *ExecSyncResponse) GetStderr() []byte {
	if x != nil {
		return x.Stderr
	}
	return nil
}

func (x *ExecSyncResponse) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

// LogsRequest subscribes to service logs.
type LogsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Project       string                 `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	Services      []string               `protobuf:"bytes,2,rep,name=services,proto3" json:"services,omitempty"`
	Follow        bool                   `protobuf:"varint,3,opt,name=follow,proto3" json:"follow,omitempty"`
	Timestamps    bool                   `protobuf:"varint,4,opt,name=timestamps,proto3" json:"timestamps,omitempty"`
	Tail          string                 `protobuf:"bytes,5,opt,name=tail,proto3" json:"tail,omitempty"`
	Since         string                 `protobuf:"bytes,6,opt,name=since,proto3" json:"since,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogsRequest) Reset() {
	*x = LogsRequest{}
	mi := &file_api_orchestrate_v1_orchestrate_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogsRequest) ProtoMessage() {}

func (x *LogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_orchestrate_v1_orchestrate_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogsRequest.ProtoReflect.Descriptor instead.
func (*LogsRequest) Descriptor() ([]byte, []int) {
	return file_api_orchestrate_v1_orchestrate_proto_rawDescGZIP(), []int{14}
}

func (x *LogsRequest) GetProject() string {
	if x != nil {
		return x.Project
	}
	return ""
}

func (x *LogsRequest) GetServices() []string {
	if x != nil {
		return x.Services
	}
	return nil
}

func (x *LogsRequest) GetFollow() bool {
	if x != nil {
		return x.Follow
	}
	return false
}

func (x *LogsRequest) GetTimestamps() bool {
	if x != nil {
		return x.Timestamps
	}
	return false
}

func (x *LogsRequest) GetTail() string {
	if x != nil {
		return x.Tail
	}
	return ""
}

func (x *LogsRequest) GetSince() string {
	if x != nil {
		return x.Since
	}
	return ""
}

// LogEntry is a single log line from a service.
type LogEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Service       string                 `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Stream        string                 `protobuf:"bytes,3,opt,name=stream,proto3" json:"stream,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogEntry) Reset() {
	*x = LogEntry{}
	mi := &file_api_orchestrate_v1_orchestrate_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogEntry) ProtoMessage() {}

func (x *LogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_api_orchestrate_v1_orchestrate_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogEntry.ProtoReflect.Descriptor instead.
func (*LogEntry) Descriptor() ([]byte, []int) {
	return file_api_orchestrate_v1_orchestrate_proto_rawDescGZIP(), []int{15}
}

func (x *LogEntry) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *LogEntry) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *LogEntry) GetStream() string {
	if x != nil {
		return x.Stream
	}
	return ""
}

func (x *LogEntry) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// DriftRequest asks the server to check for drift.
type DriftRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Project       string                 `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DriftRequest) Reset() {
	*x = DriftRequest{}
	mi := &file_api_orchestrate_v1_orchestrate_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DriftRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DriftRequest) ProtoMessage() {}

func (x *DriftRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_orchestrate_v1_orchestrate_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DriftRequest.ProtoReflect.Descriptor instead.
func (*DriftRequest) Descriptor() ([]byte, []int) {
	return file_api_orchestrate_v1_orchestrate_proto_rawDescGZIP(), []int{16}
}

func (x *DriftRequest) GetProject() string {
	if x != nil {
		return x.Project
	}
	return ""
}

// DriftItem describes a single drifted resource.
type DriftItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResourceId    string                 `protobuf:"bytes,1,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	Kind          string                 `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	Expected      string                 `protobuf:"bytes,3,opt,name=expected,proto3" json:"expected,omitempty"`
	Actual        string                 `protobuf:"bytes,4,opt,name=actual,proto3" json:"actual,omitempty"`
	Reason        string                 `protobuf:"bytes,5,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DriftItem) Reset() {
	*x = DriftItem{}
	mi := &file_api_orchestrate_v1_orchestrate_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DriftItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DriftItem) ProtoMessage() {}

func (x *DriftItem) ProtoReflect() protoreflect.Message {
	mi := &file_api_orchestrate_v1_orchestrate_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DriftItem.ProtoReflect.Descriptor instead.
func (*DriftItem) Descriptor() ([]byte, []int) {
	return file_api_orchestrate_v1_orchestrate_proto_rawDescGZIP(), []int{17}
}

func (x *DriftItem) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

func (x *DriftItem) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *DriftItem) GetExpected() string {
	if x != nil {
		return x.Expected
	}
	return ""
}

func (x *DriftItem) GetActual() string {
	if x != nil {
		return x.Actual
	}
	return ""
}

func (x *DriftItem) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// DriftResponse returns all drifted resources.
type DriftResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*DriftItem           `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DriftResponse) Reset() {
	*x = DriftResponse{}
	mi := &file_api_orchestrate_v1_orchestrate_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DriftResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DriftResponse) ProtoMessage() {}

func (x *DriftResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_orchestrate_v1_orchestrate_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DriftResponse.ProtoReflect.Descriptor instead.
func (*DriftResponse) Descriptor() ([]byte, []int) {
	return file_api_orchestrate_v1_orchestrate_proto_rawDescGZIP(), []int{18}
}

func (x *DriftResponse) GetItems() []*DriftItem {
	if x != nil {
		return x.Items
	}
	return nil
}

// RollbackRequest asks the server to rollback to a previous deployment.
type RollbackRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeploymentId  string                 `protobuf:"bytes,1,opt,name=deployment_id,json=deploymentId,proto3" json:"deployment_id,omitempty"`
	DryRun        bool                   `protobuf:"varint,2,opt,name=dry_run,json=dryRun,proto3" json:"dry_run,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RollbackRequest) Reset() {
	*x = RollbackRequest{}
	mi := &file_api_orchestrate_v1_orchestrate_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RollbackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RollbackRequest) ProtoMessage() {}

func (x *RollbackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_orchestrate_v1_orchestrate_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RollbackRequest.ProtoReflect.Descriptor instead.
func (*RollbackRequest) Descriptor() ([]byte, []int) {
	return file_api_orchestrate_v1_orchestrate_proto_rawDescGZIP(), []int{19}
}

func (x *RollbackRequest) GetDeploymentId() string {
	if x != nil {
		return x.DeploymentId
	}
	return ""
}

func (x *RollbackRequest) GetDryRun() bool {
	if x != nil {
		return x.DryRun
	}
	return false
}

// RollbackResponse returns the result of a rollback.
type RollbackResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Actions       []*Action              `protobuf:"bytes,1,rep,name=actions,proto3" json:"actions,omitempty"`
	Creates       int32                  `protobuf:"varint,2,opt,name=creates,proto3" json:"creates,omitempty"`
	Updates       int32                  `protobuf:"varint,3,opt,name=updates,proto3" json:"updates,omitempty"`
	Destroys      int32                  `protobuf:"varint,4,opt,name=destroys,proto3" json:"destroys,omitempty"`
	Noops         int32                  `protobuf:"varint,5,opt,name=noops,proto3" json:"noops,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RollbackResponse) Reset() {
	*x = RollbackResponse{}
	mi := &file_api_orchestrate_v1_orchestrate_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RollbackResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RollbackResponse) ProtoMessage() {}

func (x *RollbackResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_orchestrate_v1_orchestrate_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RollbackResponse.ProtoReflect.Descriptor instead.
func (*RollbackResponse) Descriptor() ([]byte, []int) {
	return file_api_orchestrate_v1_orchestrate_proto_rawDescGZIP(), []int{20}
}

func (x *RollbackResponse) GetActions() []*Action {
	if x != nil {
		return x.Actions
	}
	return nil
}

func (x *RollbackResponse) GetCreates() int32 {
	if x != nil {
		return x.Creates
	}
	return 0
}

func (x *RollbackResponse) GetUpdates() int32 {
	if x != nil {
		return x.Updates
	}
	return 0
}

func (x *RollbackResponse) GetDestroys() int32 {
	if x != nil {
		return x.Destroys
	}
	return 0
}

func (x *RollbackResponse) GetNoops() int32 {
	if x != nil {
		return x.Noops
	}
	return 0
}

var File_api_orchestrate_v1_orchestrate_proto protoreflect.FileDescriptor

const file_api_orchestrate_v1_orchestrate_proto_rawDesc = "" +
	"\n" +
	"$api/orchestrate/v1/orchestrate.proto\x12\x0eorchestrate.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"k\n" +
	"\vPlanRequest\x12)\n" +
	"\x10composition_json\x18\x01 \x01(\fR\x0fcompositionJson\x12\x18\n" +
	"\aproject\x18\x02 \x01(\tR\aproject\x12\x17\n" +
	"\ause_cni\x18\x03 \x01(\bR\x06useCni\"i\n" +
	"\x06Action\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x1f\n" +
	"\vresource_id\x18\x02 \x01(\tR\n" +
	"resourceId\x12\x12\n" +
	"\x04kind\x18\x03 \x01(\tR\x04kind\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason\"\xa6\x01\n" +
	"\fPlanResponse\x120\n" +
	"\aactions\x18\x01 \x03(\v2\x16.orchestrate.v1.ActionR\aactions\x12\x18\n" +
	"\acreates\x18\x02 \x01(\x05R\acreates\x12\x18\n" +
	"\aupdates\x18\x03 \x01(\x05R\aupdates\x12\x1a\n" +
	"\bdestroys\x18\x04 \x01(\x05R\bdestroys\x12\x14\n" +
	"\x05noops\x18\x05 \x01(\x05R\x05noops\"l\n" +
	"\fApplyRequest\x12)\n" +
	"\x10composition_json\x18\x01 \x01(\fR\x0fcompositionJson\x12\x18\n" +
	"\aproject\x18\x02 \x01(\tR\aproject\x12\x17\n" +
	"\ause_cni\x18\x03 \x01(\bR\x06useCni\"\xa7\x01\n" +
	"\rApplyResponse\x120\n" +
	"\aactions\x18\x01 \x03(\v2\x16.orchestrate.v1.ActionR\aactions\x12\x18\n" +
	"\acreates\x18\x02 \x01(\x05R\acreates\x12\x18\n" +
	"\aupdates\x18\x03 \x01(\x05R\aupdates\x12\x1a\n" +
	"\bdestroys\x18\x04 \x01(\x05R\bdestroys\x12\x14\n" +
	"\x05noops\x18\x05 \x01(\x05R\x05noops\"\x97\x01\n" +
	"\x0fTeardownRequest\x12\x18\n" +
	"\aproject\x18\x01 \x01(\tR\aproject\x12\x18\n" +
	"\atimeout\x18\x02 \x01(\x05R\atimeout\x12%\n" +
	"\x0eremove_volumes\x18\x03 \x01(\bR\rremoveVolumes\x12)\n" +
	"\x10composition_json\x18\x04 \x01(\fR\x0fcompositionJson\"\x12\n" +
	"\x10TeardownResponse\"(\n" +
	"\fStateRequest\x12\x18\n" +
	"\aproject\x18\x01 \x01(\tR\aproject\"}\n" +
	"\vRolloutInfo\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\tR\n" +
	"instanceId\x12!\n" +
	"\finstance_key\x18\x02 \x01(\tR\vinstanceKey\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x12\n" +
	"\x04body\x18\x04 \x01(\fR\x04body\"H\n" +
	"\rStateResponse\x127\n" +
	"\brollouts\x18\x01 \x03(\v2\x1b.orchestrate.v1.RolloutInfoR\brollouts\"\x0f\n" +
	"\rHealthRequest\"v\n" +
	"\x0eHealthResponse\x12\x18\n" +
	"\ahealthy\x18\x01 \x01(\bR\ahealthy\x12!\n" +
	"\fruntime_name\x18\x02 \x01(\tR\vruntimeName\x12'\n" +
	"\x0fruntime_version\x18\x03 \x01(\tR\x0eruntimeVersion\"q\n" +
	"\x0fExecSyncRequest\x12\x18\n" +
	"\aproject\x18\x01 \x01(\tR\aproject\x12\x18\n" +
	"\aservice\x18\x02 \x01(\tR\aservice\x12\x10\n" +
	"\x03cmd\x18\x03 \x03(\tR\x03cmd\x12\x18\n" +
	"\atimeout\x18\x04 \x01(\x03R\atimeout\"_\n" +
	"\x10ExecSyncResponse\x12\x16\n" +
	"\x06stdout\x18\x01 \x01(\fR\x06stdout\x12\x16\n" +
	"\x06stderr\x18\x02 \x01(\fR\x06stderr\x12\x1b\n" +
	"\texit_code\x18\x03 \x01(\x05R\bexitCode\"\xa5\x01\n" +
	"\vLogsRequest\x12\x18\n" +
	"\aproject\x18\x01 \x01(\tR\aproject\x12\x1a\n" +
	"\bservices\x18\x02 \x03(\tR\bservices\x12\x16\n" +
	"\x06follow\x18\x03 \x01(\bR\x06follow\x12\x1e\n" +
	"\n" +
	"timestamps\x18\x04 \x01(\bR\n" +
	"timestamps\x12\x12\n" +
	"\x04tail\x18\x05 \x01(\tR\x04tail\x12\x14\n" +
	"\x05since\x18\x06 \x01(\tR\x05since\"\x90\x01\n" +
	"\bLogEntry\x12\x18\n" +
	"\aservice\x18\x01 \x01(\tR\aservice\x128\n" +
	"\ttimestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x16\n" +
	"\x06stream\x18\x03 \x01(\tR\x06stream\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\"(\n" +
	"\fDriftRequest\x12\x18\n" +
	"\aproject\x18\x01 \x01(\tR\aproject\"\x8c\x01\n" +
	"\tDriftItem\x12\x1f\n" +
	"\vresource_id\x18\x01 \x01(\tR\n" +
	"resourceId\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind\x12\x1a\n" +
	"\bexpected\x18\x03 \x01(\tR\bexpected\x12\x16\n" +
	"\x06actual\x18\x04 \x01(\tR\x06actual\x12\x16\n" +
	"\x06reason\x18\x05 \x01(\tR\x06reason\"@\n" +
	"\rDriftResponse\x12/\n" +
	"\x05items\x18\x01 \x03(\v2\x19.orchestrate.v1.DriftItemR\x05items\"O\n" +
	"\x0fRollbackRequest\x12#\n" +
	"\rdeployment_id\x18\x01 \x01(\tR\fdeploymentId\x12\x17\n" +
	"\adry_run\x18\x02 \x01(\bR\x06dryRun\"\xaa\x01\n" +
	"\x10RollbackResponse\x120\n" +
	"\aactions\x18\x01 \x03(\v2\x16.orchestrate.v1.ActionR\aactions\x12\x18\n" +
	"\acreates\x18\x02 \x01(\x05R\acreates\x12\x18\n" +
	"\aupdates\x18\x03 \x01(\x05R\aupdates\x12\x1a\n" +
	"\bdestroys\x18\x04 \x01(\x05R\bdestroys\x12\x14\n" +
	"\x05noops\x18\x05 \x01(\x05R\x05noops2\xa0\x05\n" +
	"\x12OrchestrateService\x12A\n" +
	"\x04Plan\x12\x1b.orchestrate.v1.PlanRequest\x1a\x1c.orchestrate.v1.PlanResponse\x12D\n" +
	"\x05Apply\x12\x1c.orchestrate.v1.ApplyRequest\x1a\x1d.orchestrate.v1.ApplyResponse\x12M\n" +
	"\bTeardown\x12\x1f.orchestrate.v1.TeardownRequest\x1a .orchestrate.v1.TeardownResponse\x12D\n" +
	"\x05State\x12\x1c.orchestrate.v1.StateRequest\x1a\x1d.orchestrate.v1.StateResponse\x12G\n" +
	"\x06Health\x12\x1d.orchestrate.v1.HealthRequest\x1a\x1e.orchestrate.v1.HealthResponse\x12M\n" +
	"\bExecSync\x12\x1f.orchestrate.v1.ExecSyncRequest\x1a .orchestrate.v1.ExecSyncResponse\x12?\n" +
	"\x04Logs\x12\x1b.orchestrate.v1.LogsRequest\x1a\x18.orchestrate.v1.LogEntry0\x01\x12D\n" +
	"\x05Drift\x12\x1c.orchestrate.v1.DriftRequest\x1a\x1d.orchestrate.v1.DriftResponse\x12M\n" +
	"\bRollback\x12\x1f.orchestrate.v1.RollbackRequest\x1a .orchestrate.v1.RollbackResponseBEZCgithub.com/systemstart/nix-compose/api/orchestrate/v1;orchestratev1b\x06proto3"

var (
	file_api_orchestrate_v1_orchestrate_proto_rawDescOnce sync.Once
	file_api_orchestrate_v1_orchestrate_proto_rawDescData []byte
)

func file_api_orchestrate_v1_orchestrate_proto_rawDescGZIP() []byte {
	file_api_orchestrate_v1_orchestrate_proto_rawDescOnce.Do(func() {
		file_api_orchestrate_v1_orchestrate_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_orchestrate_v1_orchestrate_proto_rawDesc), len(file_api_orchestrate_v1_orchestrate_proto_rawDesc)))
	})
	return file_api_orchestrate_v1_orchestrate_proto_rawDescData
}

var file_api_orchestrate_v1_orchestrate_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_api_orchestrate_v1_orchestrate_proto_goTypes = []any{
	(*PlanRequest)(nil),           // 0: orchestrate.v1.PlanRequest
	(*Action)(nil),                // 1: orchestrate.v1.Action
	(*PlanResponse)(nil),          // 2: orchestrate.v1.PlanResponse
	(*ApplyRequest)(nil),          // 3: orchestrate.v1.ApplyRequest
	(*ApplyResponse)(nil),         // 4: orchestrate.v1.ApplyResponse
	(*TeardownRequest)(nil),       // 5: orchestrate.v1.TeardownRequest
	(*TeardownResponse)(nil),      // 6: orchestrate.v1.TeardownResponse
	(*StateRequest)(nil),          // 7: orchestrate.v1.StateRequest
	(*RolloutInfo)(nil),           // 8: orchestrate.v1.RolloutInfo
	(*StateResponse)(nil),         // 9: orchestrate.v1.StateResponse
	(*HealthRequest)(nil),         // 10: orchestrate.v1.HealthRequest
	(*HealthResponse)(nil),        // 11: orchestrate.v1.HealthResponse
	(*ExecSyncRequest)(nil),       // 12: orchestrate.v1.ExecSyncRequest
	(*ExecSyncResponse)(nil),      // 13: orchestrate.v1.ExecSyncResponse
	(*LogsRequest)(nil),           // 14: orchestrate.v1.LogsRequest
	(*LogEntry)(nil),              // 15: orchestrate.v1.LogEntry
	(*DriftRequest)(nil),          // 16: orchestrate.v1.DriftRequest
	(*DriftItem)(nil),             // 17: orchestrate.v1.DriftItem
	(*DriftResponse)(nil),         // 18: orchestrate.v1.DriftResponse
	(*RollbackRequest)(nil),       // 19: orchestrate.v1.RollbackRequest
	(*RollbackResponse)(nil),      // 20: orchestrate.v1.RollbackResponse
	(*timestamppb.Timestamp)(nil), // 21: google.protobuf.Timestamp
}
var file_api_orchestrate_v1_orchestrate_proto_depIdxs = []int32{
	1,  // 0: orchestrate.v1.PlanResponse.actions:type_name -> orchestrate.v1.Action
	1,  // 1: orchestrate.v1.ApplyResponse.actions:type_name -> orchestrate.v1.Action
	8,  // 2: orchestrate.v1.StateResponse.rollouts:type_name -> orchestrate.v1.RolloutInfo
	21, // 3: orchestrate.v1.LogEntry.timestamp:type_name -> google.protobuf.Timestamp
	17, // 4: orchestrate.v1.DriftResponse.items:type_name -> orchestrate.v1.DriftItem
	1,  // 5: orchestrate.v1.RollbackResponse.actions:type_name -> orchestrate.v1.Action
	0,  // 6: orchestrate.v1.OrchestrateService.Plan:input_type -> orchestrate.v1.PlanRequest
	3,  // 7: orchestrate.v1.OrchestrateService.Apply:input_type -> orchestrate.v1.ApplyRequest
	5,  // 8: orchestrate.v1.OrchestrateService.Teardown:input_type -> orchestrate.v1.TeardownRequest
	7,  // 9: orchestrate.v1.OrchestrateService.State:input_type -> orchestrate.v1.StateRequest
	10, // 10: orchestrate.v1.OrchestrateService.Health:input_type -> orchestrate.v1.HealthRequest
	12, // 11: orchestrate.v1.OrchestrateService.ExecSync:input_type -> orchestrate.v1.ExecSyncRequest
	14, // 12: orchestrate.v1.OrchestrateService.Logs:input_type -> orchestrate.v1.LogsRequest
	16, // 13: orchestrate.v1.OrchestrateService.Drift:input_type -> orchestrate.v1.DriftRequest
	19, // 14: orchestrate.v1.OrchestrateService.Rollback:input_type -> orchestrate.v1.RollbackRequest
	2,  // 15: orchestrate.v1.OrchestrateService.Plan:output_type -> orchestrate.v1.PlanResponse
	4,  // 16: orchestrate.v1.OrchestrateService.Apply:output_type -> orchestrate.v1.ApplyResponse
	6,  // 17: orchestrate.v1.OrchestrateService.Teardown:output_type -> orchestrate.v1.TeardownResponse
	9,  // 18: orchestrate.v1.OrchestrateService.State:output_type -> orchestrate.v1.StateResponse
	11, // 19: orchestrate.v1.OrchestrateService.Health:output_type -> orchestrate.v1.HealthResponse
	13, // 20: orchestrate.v1.OrchestrateService.ExecSync:output_type -> orchestrate.v1.ExecSyncResponse
	15, // 21: orchestrate.v1.OrchestrateService.Logs:output_type -> orchestrate.v1.LogEntry
	18, // 22: orchestrate.v1.OrchestrateService.Drift:output_type -> orchestrate.v1.DriftResponse
	20, // 23: orchestrate.v1.OrchestrateService.Rollback:output_type -> orchestrate.v1.RollbackResponse
	15, // [15:24] is the sub-list for method output_type
	6,  // [6:15] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_api_orchestrate_v1_orchestrate_proto_init() }
func file_api_orchestrate_v1_orchestrate_proto_init() {
	if File_api_orchestrate_v1_orchestrate_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_orchestrate_v1_orchestrate_proto_rawDesc), len(file_api_orchestrate_v1_orchestrate_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_orchestrate_v1_orchestrate_proto_goTypes,
		DependencyIndexes: file_api_orchestrate_v1_orchestrate_proto_depIdxs,
		MessageInfos:      file_api_orchestrate_v1_orchestrate_proto_msgTypes,
	}.Build()
	File_api_orchestrate_v1_orchestrate_proto = out.File
	file_api_orchestrate_v1_orchestrate_proto_goTypes = nil
	file_api_orchestrate_v1_orchestrate_proto_depIdxs = nil
}
